import { cp, mkdir, rm, writeFile } from "node:fs/promises";
import path from "node:path";

const rootDir = process.cwd();
const outputDir = path.join(rootDir, "deploy", "plesk");
const backendSrcDir = path.join(rootDir, "backend");
const frontendDistDir = path.join(rootDir, "frontend", "dist");
const uploadsSrcDir = path.join(rootDir, "uploads");

const backendOutDir = path.join(outputDir, "backend");
const frontendOutDir = path.join(outputDir, "frontend", "httpdocs");
const uploadsOutDir = path.join(outputDir, "uploads");

async function prepareOutput() {
  await rm(outputDir, { recursive: true, force: true });
  await mkdir(outputDir, { recursive: true });
}

function backendFilter(src) {
  const name = path.basename(src);
  const blocked = new Set([
    "node_modules",
    "uploads",
    ".env",
    ".git",
    ".DS_Store",
    "npm-debug.log",
  ]);
  return !blocked.has(name);
}

async function copyBackend() {
  await cp(backendSrcDir, backendOutDir, {
    recursive: true,
    filter: backendFilter,
  });
}

async function copyFrontendBuild() {
  await cp(frontendDistDir, frontendOutDir, { recursive: true });
}

async function copyUploads() {
  await cp(uploadsSrcDir, uploadsOutDir, { recursive: true });
}

async function writeDeploymentReadme() {
  const deploymentReadmePath = path.join(outputDir, "DEPLOYMENT.txt");
  const content = [
    "PLESK DEPLOYMENT PACKAGE",
    "",
    "Layout:",
    "- backend/: Node.js API app (set startup file to server.js)",
    "- frontend/httpdocs/: static frontend files for admin domain",
    "- uploads/: shared uploads mounted by backend at /uploads",
    "",
    "Required steps in Plesk:",
    "1) Backend domain (api.admin.hezzni.com)",
    "   - Application root: backend",
    "   - Startup file: server.js",
    "   - Node.js: 18+",
    "   - Run npm install in backend",
    "   - Set backend environment variables (DB_*, JWT_SECRET, ADMIN_*)",
    "   - Set UPLOADS_DIR=../uploads",
    "",
    "2) Frontend domain (admin.hezzni.com)",
    "   - Upload frontend/httpdocs contents into domain httpdocs",
    "   - Ensure .htaccess exists for SPA routing",
    "",
    "3) Shared uploads",
    "   - Keep uploads folder beside backend",
    "",
    "Generated by scripts/prepare-plesk.mjs",
  ].join("\n");

  await writeFile(deploymentReadmePath, content, "utf8");
}

async function main() {
  await prepareOutput();
  await Promise.all([copyBackend(), copyFrontendBuild(), copyUploads()]);
  await writeDeploymentReadme();
  console.log(`Plesk bundle created at: ${outputDir}`);
}

main().catch((error) => {
  console.error("Failed to prepare Plesk bundle:", error);
  process.exit(1);
});
